#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely and handles SIGTERM signal

# Function to handle SIGTERM
handle_sigterm() {
    echo "I am invincible!!!"
}

# Trap SIGTERM signal and call the handler function
trap handle_sigterm SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
