#!/usr/bin/env bash
# A Bash script that displays "To infinity and beyond" indefinitely
# and handles SIGTERM signal

# Function to handle SIGTERM signal
handle_sigterm() {
  echo "I am invincible!!!"
}

# Trap the SIGTERM signal and call the handle_sigterm function
trap handle_sigterm SIGTERM

while true
do
  echo "To infinity and beyond"
  sleep 2
done
