#!/usr/bin/env bash
# This script displays numbers from 1 to 20 with additional messages
i=1
while [ $i -le 20 ]; do
  case $i in
    4) echo -n "$i bad luck from China";;
    9) echo -n "$i bad luck from Japan";;
    17) echo -n "$i bad luck from Italy";;
    *) echo -n "$i";;
  esac
  echo
  i=$((i + 1))
done
